language: java

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE carpnd;'
  - mysql -e 'CREATE TABLE carpnd.users(
              cuil VARCHAR(11) NOT NULL UNIQUE,
                 name VARCHAR(30),
                 surname VARCHAR(30),
                 address VARCHAR(50),
                 email VARCHAR(50),
                 PRIMARY KEY (cuil)
              );'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('admin') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn clean verify


notifications:
  email:
    - mvmarkon@gmail.com
    - mverdecanna@gmail.com
test:
  - mvn test -B
after_success:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=c2459292e6ef48c19cbed79c5f52e794 -DapiToken=8FM6usGXT53exDRxiOos