language: java

before_script:
  - cd desapp-groupD-backend

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn clean verify

notifications:
  email:
    - mvmarkon@gmail.com
    - mverdecanna@gmail.com
test:
  - mvn test -B

deploy:

  - provider: heroku

    skip_cleanup: true
    app:desapp-unq-grupo-d-frontend 
