language: java

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

services:
  - mysql

script: mvn clean verify

before_install:
  - mysql -e 'CREATE DATABASE carpnd;'
  - mysql -e 'CREATE TABLE carpnd.users(
      cuil VARCHAR(11) NOT NULL UNIQUE, name VARCHAR(30), surname VARCHAR(30), address VARCHAR(50), email VARCHAR(50),
      PRIMARY KEY (cuil) );'
notifications:
  email:
    - mvmarkon@gmail.com
    - mverdecanna@gmail.com
test:
  - mvn test -B
after_success:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=c2459292e6ef48c19cbed79c5f52e794 -DapiToken=8FM6usGXT53exDRxiOos