language: java

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

services:
  - mysql

script: mvn clean verify

before_install:
  - mysql -e 'CREATE DATABASE carpnd;'
  - mysql -e 'CREATE TABLE carpnd.users(
      cuil VARCHAR(11) NOT NULL UNIQUE, name VARCHAR(30), surname VARCHAR(30), address VARCHAR(50), email VARCHAR(50),
      PRIMARY KEY (cuil) );'
  - mysql -e 'CREATE TABLE carpnd.current_account(
        cuil VARCHAR(11) NOT NULL UNIQUE, credits INTEGER(8),
        PRIMARY KEY (cuil) );'
  - mysql -e 'CREATE TABLE carpnd.vehicles(
        id VARCHAR(8) NOT NULL UNIQUE, type VARCHAR(10) NOT NULL, capacity INTEGER(2), location VARCHAR(50), retirementAddress VARCHAR(255),
        returnAddress VARCHAR(255), description VARCHAR(50), phone VARCHAR(50), cost INTEGER(4), ownerCuil VARCHAR(11), photo VARCHAR(255), PRIMARY KEY (id) );'
  - mysql -e 'CREATE TABLE carpnd.rental(
        id INTEGER(8) NOT NULL AUTO_INCREMENT, state VARCHAR(12) NOT NULL, startDate DATETIME, endDate DATETIME,
        ownerCuil VARCHAR(11), clientCuil VARCHAR(11), vehicle_id VARCHAR(8),
        PRIMARY KEY (id) );'
  - mysql -e 'CREATE TABLE carpnd.transactions(
	    id INTEGER(8) NOT NULL UNIQUE, state VARCHAR(12) NOT NULL, cost INTEGER, created DATETIME, lastUpdated DATETIME,
        PRIMARY KEY (id) );'
  - mysql -e 'CREATE TABLE carpnd.scores(
      	id INTEGER(8) NOT NULL AUTO_INCREMENT, value INTEGER, comment VARCHAR(255), transactionID INTEGER(8), userCuil VARCHAR(11), creator VARCHAR(11),
      PRIMARY KEY (id) );'


notifications:
  email:
    - mvmarkon@gmail.com
    - mverdecanna@gmail.com
test:
  - mvn test -B
after_success:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=c2459292e6ef48c19cbed79c5f52e794 -DapiToken=8FM6usGXT53exDRxiOos