language: java


build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn clean verify


notifications:
  email:
    - mvmarkon@gmail.com
    - mverdecanna@gmail.com
test:
  - mvn test -B
after_success:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=c2459292e6ef48c19cbed79c5f52e794 -DapiToken=8FM6usGXT53exDRxiOos